---
title: "Untitled"
format: html
editor: visual
---

```{r}
# A 2x2 matrix
karlsruhe_bb <- matrix(data = c(
   8.3549,
  8.4349,
  48.9868,
  49.0255
 
  ),
                    nrow = 2,
                    byrow = TRUE)

# Update column and row names
colnames(karlsruhe_bb) <- c("min", "max")
rownames(karlsruhe_bb) <- c("x", "y")
```

## Create Street Network
```{r}
# Extract streets
highway <- karlsruhe_bb %>%
  opq() %>%
  add_osm_feature(key = "highway") %>%
  osmdata_sf()

streets <- highway$osm_lines
names(streets)


# Plot with ggplot
ggplot() +
  geom_sf(data = streets,
          inherit.aes = FALSE,
          color = "black",
          size = 0.2)


# Convert object to sfnetwork object
# Source: https://geospatial-community.netlify.app/post/2022-03-31-spatial-networks/
street_net <- as_sfnetwork(streets, directed = FALSE) # set as undirected

street_net
```

```{r}
# Store edges in variable
edges <- street_net %>% activate(edges) %>% st_as_sf()

# Union
edges <- st_union(edges)

# Get nearest point for each GPS location
nearest <- st_nearest_points(data, edges)



```


